### ISSUE TITLE
shitty-highlighter: markdown highlighting

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#720] opened 2021-09-02 15:31 UTC
When I scroll down the fancy code block highlighting disappears

![image](https://user-images.githubusercontent.com/77941087/131872540-3b33fac6-2242-4e83-98f8-b5f627d06e97.png)
![image](https://user-images.githubusercontent.com/77941087/131872482-ba6322b2-e134-41cf-aaf8-5871d15c6726.png)

**Comment by Akuli** [comment] 2021-09-03 05:12
Duplicate of #420

**Closed by Akuli** 2021-09-03 05:12 UTC
