### ISSUE TITLE
AssertionError: something hasn't cleaned up its tabs

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1331] opened 2023-07-04 02:32 UTC
I get this error somewhat often when executing tests. I usually just restart porcupine a couple times and rerun the tests till it goes away. Any idea what could be causing this?

**Comment by Moosems** [comment] 2023-07-04 16:44
Related to #1193?

**Comment by Akuli** [comment] 2023-07-04 19:12
This error happens when a test leaves tabs into the tab manager for whatever reason, and its purpose is to prevent existing tabs from messing up tests that expect the tab manager to be empty. If you can reproduce this, maybe with a failing test to get that assertion error, that would be nice :)

The error isn't supposed to happen even if a test fails, because the `tabmanager` fixture attempts to close all tabs after a test finishes, regardless of whether it succeeded or not.

**Comment by benjamin-kirkbride** [comment] 2023-07-04 19:20
Where is the state stored?

**Comment by Akuli** [comment] 2023-07-04 19:28
It is in the global `TabManager` widget, accessible with `get_tab_manager()`.

**Comment by benjamin-kirkbride** [comment] 2023-07-04 19:37
I mean where is it stored between runs, like where would it be in between tests?

**Comment by Akuli** [comment] 2023-07-04 19:46
All tests use the same tab manager. For "storing" the tabs, it just adds them to the underlying tkinter widget, and asks it what widgets it contains when you need to know what tabs there are.

I feel like maybe one of us is missing something obvious.

**Comment by benjamin-kirkbride** [comment] 2023-07-04 19:49
Yeah sorry, I guess my confusion is coming from how it seems like there is some sort of "state" persisting between runs for 2 reasons:
1. this problem appears much more often (exclusively?) when I have another instance of porcupine running; as in I have an instance running normally, then I start pytest
2. when "the problem" starts, it takes a few times of me starting pytest, killing pytest, letting pytest finish, waiting, etc for it to stop being a problem. Then it is fine for a long time.

The above has led me to assume there is some sort of state that is shared between the sessions of Porcupine that might not be properly cleaned up, but that may be a bad assumption.

**Comment by Akuli** [comment] 2023-07-04 19:59
That's the confusion. I now understand what you mean with state.

> this problem appears much more often (exclusively?) when I have another instance of porcupine running; as in I have an instance running normally, then I start pytest

One thing that sometimes confuses the tests is whether your keyboard/input focus is in the test window or some other window.

> when "the problem" starts, it takes a few times of me starting pytest, killing pytest, letting pytest finish, waiting, etc for it to stop being a problem. Then it is fine for a long time.

Sounds like something that the restart plugin could cause. It has a state file, and it uses it to restore previously opened tabs when you close and reopen Porcupine. So when you manage this thing to "stop being a problem", it could mean you ending up with a restart state file that has no tabs in it (or no state file).

Ideally the restart plugin wouldn't restore tabs when a test run starts, but I don't remember ever ensuring this doesn't happen. I just haven't realized that it could be a problem. There is already a setting that disables it, maybe we could somehow enable that for test sessions?

It could also be something else than the restart plugin, but I don't think there are other state files (except the settings json and font cache).

**Comment by benjamin-kirkbride** [comment] 2023-07-05 01:13
https://dpaste.org/TcmFL

Here is a paste of the most recent 3k lines with this issue.

> One thing that sometimes confuses the tests is whether your keyboard/input focus is in the test window or some other window.

I don't notice a difference with doing headless testing.

So funny thing is I ran pytest and got the dpaste above, then I ran it again and t was completely fine. No changes. :shrug:

**Comment by Akuli** [comment] 2023-07-06 21:52
This just happened to me. I can confirm it's the restart plugin loading up tabs that I had open when I used porcupine last time.

**Comment by benjamin-kirkbride** [comment] 2023-07-10 22:19
Can we explicitly nuke them when pytest starts? or maybe have pytest create a clean set of dirs to use?

**Comment by Akuli** [comment] 2023-07-11 12:44
Good question. Because you poked me in the right direction, I now know what the problem is :)

There are already clean dirs, see `monkeypatch_dirs()` in conftest.py. This means that before any test functions runs, `porcupine.dirs` is changed to point at freshly created temporary dirs. The problem is that `plugins/restart.py` uses `porcupine.dirs` at *import time*, which is too early.

See `_get_path()` in `plugins/run/history.py` for an example of how to do this correctly.

**Comment by benjamin-kirkbride** [comment] 2023-07-11 21:11
since this is a common pattern, should we consider re-working the `dirs` api?

**Comment by Akuli** [comment] 2023-07-11 21:52
I don't think it can be improved much. Even with an explicit function call like `dirs.get_foo_path()`, you could assign it to a global variable. Maybe that would more obviously look like a bug though.

**Closed** 2023-07-11 21:53 UTC
